"""C++ cross-validation용 기준 데이터 생성.

두 종류의 파일을 만든다.

1. results/crossval_hamiltonians/<molecule>_R<R>.txt
   CLI의 TERMS 블록 형식. 외부 의존성 없이 읽히는 텍스트.
       TERMS <m>
       <coeff> <label>
   항 순서는 sqd_vqe/data/*.json과 동일하게 유지한다 (정렬된 순서).
   부동소수점 합산 순서를 양쪽에서 통일하기 위함.

2. results/crossval_states.txt
   한 줄에 (molecule, R, kind, dim, 2d개 double, energy).
   Hamiltonian 파일은 항상 <molecule>_R<R>.txt 로 찾으면 된다 — 예외 없음.

행의 종류 (kind 열):
  vqe     : VQE가 수렴한 state. 분자 Hamiltonian
  random  : Haar-random 복소 state. 복소 진폭 처리 경로 검증

molecule 열의 종류:
  h2, lih            : 분자. 21 + 14개 R
  random_d4/_d16     : 분자 Hamiltonian + 랜덤 state
  ycomplex_d4/_d16   : 분자 Hamiltonian에 Y 홀수 항을 더한 합성 + 랜덤 state

ycomplex가 필요한 이유:
  분자 Hamiltonian은 실수 대칭 행렬이다. Pauli string은 Y 개수가 짝수일 때만
  실수 행렬이고, 분자 Hamiltonian은 적분이 실수라 항상 짝수 Y만 나온다.
  실수 H에서는 <psi|H|psi> 와 켤레를 반대쪽에 건 psi^T H psi* 가 복소 psi에
  대해서도 항등적으로 같다. 즉 랜덤 복소 state만으로는 켤레 방향 버그가
  드러나지 않는다. Y가 홀수인 항을 넣어야 두 값이 갈린다.
  (합성 Hamiltonian도 Hermitian이다: Pauli string은 Hermitian이고 계수가 실수)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from sqd_vqe.ansatz import (
    H2_NUM_PARAMS,
    LIH_NUM_PARAMS,
    h2_ansatz_state,
    lih_ansatz_state,
)
from sqd_vqe.expectation import expectation_value, hamiltonian_matrix
from sqd_vqe.hamiltonian import (
    PauliHamiltonian,
    get_h2_hamiltonian,
    get_lih_hamiltonian,
)
from sqd_vqe.sweep import PAPER_H2_DISTANCES, PAPER_LIH_DISTANCES
from sqd_vqe.vqe import run_vqe_multistart


STATES_PATH = Path("results/crossval_states.txt")
HAM_DIR = Path("results/crossval_hamiltonians")

VQE_SEED = 42
RANDOM_STATE_SEED = 20260926
N_RANDOM_STATES = 5

# 랜덤 state를 붙일 기준 분자/거리
ANCHOR_H2_R = 0.73
ANCHOR_LIH_R = 1.55

# 켤레 방향 검증용으로 더할 Y 홀수 항 (계수는 분자 항과 비슷한 크기)
ODD_Y_TERMS_D4 = [("IY", 0.137), ("XY", -0.091), ("YZ", 0.223)]
ODD_Y_TERMS_D16 = [("IIIY", 0.137), ("IXYZ", -0.091), ("YZZX", 0.223)]


def g17(x: float) -> str:
    """double을 왕복 변환 가능한 최소 자릿수로."""
    return f"{x:.17g}"


def ham_filename(molecule: str, R: float) -> str:
    return f"{molecule}_R{R:.4f}.txt"


def write_hamiltonian(molecule: str, R: float, H: PauliHamiltonian) -> None:
    """TERMS 블록 형식으로 Hamiltonian을 덤프."""
    lines = [f"TERMS {len(H.terms)}"]
    for label, coeff in H.terms:
        lines.append(f"{g17(coeff)} {label}")
    path = HAM_DIR / ham_filename(molecule, R)
    path.write_text("\n".join(lines) + "\n")


def with_odd_y(H: PauliHamiltonian, extra) -> PauliHamiltonian:
    """기존 Hamiltonian에 Y 홀수 항을 더한 합성 Hamiltonian.

    Pauli string은 Hermitian이고 계수가 실수이므로 결과도 Hermitian이다.
    단, 행렬은 더 이상 실수가 아니다 — 그게 목적이다.
    """
    n = len(H.terms[0][0])
    for label, _ in extra:
        assert len(label) == n, (label, n)
        assert label.count("Y") % 2 == 1, f"{label} must have an odd Y count"

    existing = dict(H.terms)
    for label, coeff in extra:
        assert label not in existing, f"{label} already present"
        existing[label] = coeff

    terms = sorted(existing.items(), key=lambda t: t[0])
    return PauliHamiltonian(terms=terms, nuclear_repulsion=H.nuclear_repulsion)


def haar_random_state(rng, dim: int) -> np.ndarray:
    """Haar-uniform 복소 단위 벡터.

    복소 정규분포를 뽑아 정규화하면 단위구 위에서 Haar-uniform이다.
    """
    v = rng.normal(size=dim) + 1j * rng.normal(size=dim)
    return v / np.linalg.norm(v)


def row(molecule: str, R: float, kind: str,
        psi: np.ndarray, energy: float) -> str:
    amps = " ".join(f"{g17(c.real)} {g17(c.imag)}" for c in psi)
    return f"{molecule} {R:.4f} {kind} {len(psi)} {amps} {g17(energy)}"


def check_state(psi: np.ndarray, H: PauliHamiltonian, where: str) -> None:
    norm_sq = float(np.vdot(psi, psi).real)
    assert abs(norm_sq - 1.0) < 1e-12, (where, norm_sq)
    assert len(psi) == H.dimension, (where, len(psi), H.dimension)


def main():
    HAM_DIR.mkdir(parents=True, exist_ok=True)
    STATES_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# C++ cross-validation reference data",
        "# Generated by tools/dump_crossval_states.py",
        "#",
        "# columns:",
        "#   molecule R kind dim re0 im0 re1 im1 ... re(d-1) im(d-1) energy",
        "#",
        "# The Hamiltonian for a row is always",
        "#   crossval_hamiltonians/<molecule>_R<R>.txt",
        "# with R written exactly as in column 2. No special cases.",
        "#",
        "# energy is <psi|H|psi> recomputed from the state vector on this",
        "# same line, so each row is self-consistent by construction.",
        "# All doubles except R use %.17g. R uses %.4f as a lookup key.",
        "#",
        "# kind=vqe    : the state a converged VQE run produced",
        "# kind=random : Haar-random complex state, seed "
        f"{RANDOM_STATE_SEED}",
        "#",
        "# molecule=ycomplex_* carries a synthetic Hamiltonian: the molecular",
        "# one plus terms with an odd number of Y. Molecular Hamiltonians are",
        "# real symmetric, and for a real H the expectation value is",
        "# unchanged if the conjugation is applied to the wrong side --",
        "# so those rows alone cannot catch that bug. These rows can.",
    ]

    max_drift = 0.0

    # --- 1. VQE가 수렴한 state (분자) -------------------------------------
    vqe_cases = [
        ("h2", PAPER_H2_DISTANCES, get_h2_hamiltonian,
         h2_ansatz_state, H2_NUM_PARAMS, 3),
        ("lih", PAPER_LIH_DISTANCES, get_lih_hamiltonian,
         lih_ansatz_state, LIH_NUM_PARAMS, 5),
    ]

    for name, distances, ham_fn, ansatz, n_params, n_restarts in vqe_cases:
        print(f"[vqe] {name}: {len(distances)} distances, "
              f"multi-start {n_restarts}")
        for R in distances:
            H = ham_fn(distance=float(R))
            write_hamiltonian(name, float(R), H)

            result = run_vqe_multistart(
                H, ansatz=ansatz, n_restarts=n_restarts,
                seed=VQE_SEED, n_params=n_params,
            )
            psi = ansatz(result.params)
            check_state(psi, H, f"{name} R={R}")

            # 파일에 적는 energy는 psi에서 다시 계산한다. SciPy의 result.fun은
            # '평가된 값 중 최소'이고 result.x가 정확히 그 지점이라는 보장이
            # 문서상 명시적이지 않다. C++은 psi만 받아 계산하므로 기준값도
            # psi에서 나와야 비교가 구현 차이만 재게 된다.
            energy = expectation_value(psi, H)
            max_drift = max(max_drift, abs(energy - result.energy))

            lines.append(row(name, float(R), "vqe", psi, energy))
            print(f"  R={R:.2f}  E={energy:+.12f}")

    # --- 2. 랜덤 복소 state ----------------------------------------------
    rng = np.random.default_rng(RANDOM_STATE_SEED)

    anchors = [
        ("random_d4", ANCHOR_H2_R, get_h2_hamiltonian(distance=ANCHOR_H2_R)),
        ("random_d16", ANCHOR_LIH_R,
         get_lih_hamiltonian(distance=ANCHOR_LIH_R)),
    ]

    for molecule, R, H in anchors:
        write_hamiltonian(molecule, R, H)
        print(f"[random] {molecule}: dim={H.dimension}, "
              f"{N_RANDOM_STATES} states")
        for _ in range(N_RANDOM_STATES):
            psi = haar_random_state(rng, H.dimension)
            check_state(psi, H, molecule)
            energy = expectation_value(psi, H)
            lines.append(row(molecule, R, "random", psi, energy))
            print(f"  E={energy:+.12f}")

    # --- 3. Y 홀수 항을 더한 합성 Hamiltonian + 랜덤 state ----------------
    synthetic = [
        ("ycomplex_d4", ANCHOR_H2_R,
         with_odd_y(get_h2_hamiltonian(distance=ANCHOR_H2_R),
                    ODD_Y_TERMS_D4)),
        ("ycomplex_d16", ANCHOR_LIH_R,
         with_odd_y(get_lih_hamiltonian(distance=ANCHOR_LIH_R),
                    ODD_Y_TERMS_D16)),
    ]

    for molecule, R, H in synthetic:
        write_hamiltonian(molecule, R, H)
        M = hamiltonian_matrix(H)
        assert not np.allclose(M.imag, 0), f"{molecule} matrix is still real"
        assert np.allclose(M, M.conj().T), f"{molecule} is not Hermitian"

        print(f"[ycomplex] {molecule}: dim={H.dimension}, "
              f"{len(H.terms)} terms, matrix is complex")
        for _ in range(N_RANDOM_STATES):
            psi = haar_random_state(rng, H.dimension)
            check_state(psi, H, molecule)
            energy = expectation_value(psi, H)

            # 켤레를 반대쪽에 걸면 실제로 값이 달라지는지 확인.
            # 이게 갈리지 않으면 이 행은 목적을 달성하지 못한다.
            flipped = complex(psi @ M @ psi.conj())
            assert not np.isclose(energy, flipped.real), (
                f"{molecule}: conjugation direction is not distinguished"
            )

            lines.append(row(molecule, R, "random", psi, energy))
            print(f"  E={energy:+.12f}  (flipped would give "
                  f"{flipped.real:+.12f})")

    STATES_PATH.write_text("\n".join(lines) + "\n")

    n_rows = sum(1 for l in lines if not l.startswith("#"))
    n_ham = len(list(HAM_DIR.glob("*.txt")))
    print(f"\nWrote {n_rows} rows to {STATES_PATH}")
    print(f"Wrote {n_ham} Hamiltonians to {HAM_DIR}/")
    print(f"Max |E(psi) - result.energy| over VQE rows: {max_drift:.2e}")
    if max_drift > 1e-12:
        print("  NOTE: result.x and result.fun do not correspond exactly.")
        print("  The file uses E(psi), which is what C++ must match.")


if __name__ == "__main__":
    main()